function(add_resource INPUT_FILE_PATH OUTPUT_FILE_PATH OUTPUT_VAR_NAME)
	file(READ "${INPUT_FILE_PATH}" hex_content HEX)
	foreach(a RANGE 31)
		string(CONCAT pattern "[0-9a-f]" pattern)
	endforeach(a RANGE 31)
	string(REGEX REPLACE "(${pattern})" "\\1\n" content "${hex_content}")
	string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " content "${content}")
	string(REGEX REPLACE ", $" "" content "${content}")
	string(MAKE_C_IDENTIFIER ${OUTPUT_VAR_NAME} C_STYLE_OUTPUT_VAR_NAME)
	set(array_definition "static const unsigned char ${C_STYLE_OUTPUT_VAR_NAME}[] =\n{\n${content}\n};")
	set(source "${array_definition}\n")
	file(WRITE "${OUTPUT_FILE_PATH}" "${source}")
endfunction()

function(get_resources PATH COMPILED_RESOURCES)
	FILE(GLOB_RECURSE RESOURCE_LIST ${PATH})
	FOREACH(INPUT_FILE ${RESOURCE_LIST})
		get_filename_component(RELATIVE_PATH ${INPUT_FILE} REALPATH)
		get_filename_component(FILE_NAME ${INPUT_FILE} NAME_WE)
		SET(OUTPUT_FILE ${CMAKE_CURRENT_BINARY_DIR}/resources/${FILE_NAME}_xml.h)
		add_resource(${RELATIVE_PATH} ${OUTPUT_FILE} ${FILE_NAME}_xml)
		LIST(APPEND ${COMPILED_RESOURCES} ${OUTPUT_FILE})
	ENDFOREACH()
endfunction()
